name: build and deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Pack and publish
        run: dotnet pack PdfTurtleClientDotnet/PdfTurtleClientDotnet.csproj --configuration Release  --no-build
      # - run: dotnet nuget push PdfTurtleClientDotnet/bin/Release/PdfTurtleClientDotnet.*.nupkg --api-key
